name: PassengerMobs
version: ${project.version}
main: net.kunmc.lab.passengermobs.PassengerMobs
api-version: 1.16
description: 重ねモブプラグイン

commands:
  PassengerMobs:
    aliases: [pm]
    usage: |
      /<command> radius <number> : スポーン時にMobが重なりうる範囲を指定
    permission: op